import React from "react";
import { Collab as _Collab } from "./Collab";
import { makeAppStore } from "../../stores/AppStore";

export default {
  title: "PopUpActivities/Collab",
  component: Collab,
};

const settings = {
  settings: {
    assets: "https://cie-assets.nyc3.digitaloceanspaces.com",
    websocketAddress: "ws://127.0.0.1:5000/ws/stream",
  },
};

class FakeWebsocket {
  send(data) {
    console.log(`fake websocket send() data:`, data);
  }
}
const websocket = new FakeWebsocket();
const model = {
  canvasData: {
    version: "4.4.0",
    objects: [
      {
        type: "rect",
        version: "4.4.0",
        originX: "left",
        originY: "top",
        left: 271,
        top: 244,
        width: 50,
        height: 50,
        fill: "rgb(0,0,0)",
        stroke: null,
        strokeWidth: 1,
        strokeDashArray: null,
        strokeLineCap: "butt",
        strokeDashOffset: 0,
        strokeLineJoin: "miter",
        strokeUniform: false,
        strokeMiterLimit: 4,
        scaleX: 3.49,
        scaleY: 3.49,
        angle: 0,
        flipX: false,
        flipY: false,
        opacity: 1,
        shadow: null,
        visible: true,
        backgroundColor: "",
        fillRule: "nonzero",
        paintFirst: "fill",
        globalCompositeOperation: "source-over",
        skewX: 0,
        skewY: 0,
        rx: 0,
        ry: 0,
        id: "93627178-60c9-41c0-bec1-72cb962a5e05",
      },
      {
        type: "circle",
        version: "4.4.0",
        originX: "left",
        originY: "top",
        left: 220,
        top: 280,
        width: 100,
        height: 100,
        fill: "black",
        stroke: null,
        strokeWidth: 1,
        strokeDashArray: null,
        strokeLineCap: "butt",
        strokeDashOffset: 0,
        strokeLineJoin: "miter",
        strokeUniform: false,
        strokeMiterLimit: 4,
        scaleX: 1,
        scaleY: 1,
        angle: 0,
        flipX: false,
        flipY: false,
        opacity: 1,
        shadow: null,
        visible: true,
        backgroundColor: "",
        fillRule: "nonzero",
        paintFirst: "fill",
        globalCompositeOperation: "source-over",
        skewX: 0,
        skewY: 0,
        radius: 50,
        startAngle: 0,
        endAngle: 6.283185307179586,
        id: "ca28a2f6-05d8-42e3-93dd-e50a3e0ae87c",
      },
      {
        type: "circle",
        version: "4.4.0",
        originX: "left",
        originY: "top",
        left: 399,
        top: 279,
        width: 100,
        height: 100,
        fill: "black",
        stroke: null,
        strokeWidth: 1,
        strokeDashArray: null,
        strokeLineCap: "butt",
        strokeDashOffset: 0,
        strokeLineJoin: "miter",
        strokeUniform: false,
        strokeMiterLimit: 4,
        scaleX: 0.99,
        scaleY: 0.99,
        angle: 0,
        flipX: false,
        flipY: false,
        opacity: 1,
        shadow: null,
        visible: true,
        backgroundColor: "",
        fillRule: "nonzero",
        paintFirst: "fill",
        globalCompositeOperation: "source-over",
        skewX: 0,
        skewY: 0,
        radius: 50,
        startAngle: 0,
        endAngle: 6.283185307179586,
        id: "77f8cd48-f3bb-486e-bd6e-6b5347f83c35",
      },
      {
        type: "image",
        version: "4.4.0",
        originX: "left",
        originY: "top",
        left: 267.4,
        top: 51.4,
        width: 512,
        height: 512,
        fill: "rgb(0,0,0)",
        stroke: null,
        strokeWidth: 0,
        strokeDashArray: null,
        strokeLineCap: "butt",
        strokeDashOffset: 0,
        strokeLineJoin: "miter",
        strokeUniform: false,
        strokeMiterLimit: 4,
        scaleX: 0.36,
        scaleY: 0.36,
        angle: 0,
        flipX: false,
        flipY: false,
        opacity: 1,
        shadow: null,
        visible: true,
        backgroundColor: "",
        fillRule: "nonzero",
        paintFirst: "fill",
        globalCompositeOperation: "source-over",
        skewX: 0,
        skewY: 0,
        cropX: 0,
        cropY: 0,
        id: "9c4e91cb-2823-4512-bab9-11b97a0384c8",
        src: "https://image.flaticon.com/icons/png/512/115/115804.png",
        crossOrigin: null,
        filters: [],
      },
    ],
  },
  exerciseTitle: "dsfsd",
  exerciseObjectProperties: [
    {
      uuid: "9c4e91cb-2823-4512-bab9-11b97a0384c8",
      lockMovementX: true,
      lockMovementY: true,
    },
    {
      uuid: "77f8cd48-f3bb-486e-bd6e-6b5347f83c35",
      lockMovementX: true,
      lockMovementY: true,
    },
    {
      uuid: "9c4e91cb-2823-4512-bab9-11b97a0384c8",
      lockMovementX: false,
      lockMovementY: false,
    },
  ],
  studentDrawOptions: {
    addImages: true,
    addShapes: true,
    addText: true,
    freeDraw: true,
  },
};

const appStore = makeAppStore();
appStore.userId = 1;

let props = {
  model,
  ...settings,
  websocket,
  appStore,
};

export const Collab = () => <_Collab {...props} />;
