apiVersion: v1
kind: Service
metadata:
  name: cie-db
spec:
  ports:
  - port: 3306
  selector:
    app: cie-db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cie-db
spec:
  serviceName: cie-db
  selector:
    matchLabels:
      app: cie-db
  template:
    metadata:
      labels:
        app: cie-db
    spec:
      volumes:
        - name: db-pv-storage
          persistentVolumeClaim:
            claimName: db-pv-claim
      containers:
      - image: mysql/mysql-server:8.0
        name: cie-db
        envFrom:
        - secretRef:
            name: cie-db-user-creds
        ports:
        - containerPort: 3306
          name: cie-db
        volumeMounts:
        - name: db-pv-storage
          mountPath: "/data"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi