#! /usr/bin/node

const { createLoadBalancer, createService, createDeployment, argv } = require('./util');

const YAML = require('json-to-pretty-yaml');


const deployEnv = argv.e;
const COMPONENT_NAME = 'cie-web';

let service;
if (deployEnv == 'local' || deployEnv == 'dev') {
    // if dev, create an LB for use with MetalLB
    service = createLoadBalancer(
        COMPONENT_NAME,
        argv.externalIP || '192.168.1.43',
        80,
        80
    );
} else if (deployEnv === 'prod') {
    // if prod, use a simple service
    service = createService(
        COMPONENT_NAME,
        80,
        80
    );
}
service.validate();


let deployment = createDeployment({
    componentName: COMPONENT_NAME,
    imageName: 'vengelmann/cie-web',
    envVars: [{ name: 'CIE_ENV', value: deployEnv }],
    ports: [{ 'containerPort': 80 }]
});

console.log(YAML.stringify(service));
console.log('---');
console.log(YAML.stringify(deployment));