#! /usr/bin/node
const { createService, createDeployment, argv } = require('./util');
const YAML = require('json-to-pretty-yaml');


const deployEnv = argv.e;
const COMPONENT_NAME = "cie-api";

let apiSvc = createService(
    COMPONENT_NAME,
    80,
    "http"
);

apiSvc.validate();

let apiDeploy = createDeployment({
    componentName: COMPONENT_NAME,
    imageName: "vengelmann/cie-api",
    envVars: [{ name: "CIE_ENV", value: deployEnv }],
    ports: [{ name: "http", containerPort: 80 }],
    secrets: "regcred"
});


const svcYml = YAML.stringify(apiSvc);
console.log(svcYml);
console.log("---")
const deployYml = YAML.stringify(apiDeploy);
console.log(deployYml);



