#! /usr/bin/node

const { createLoadBalancer, createDeployment, argv } = require('./util');

const YAML = require('json-to-pretty-yaml');


  
const deployEnv = argv.e;
const COMPONENT_NAME = 'cie-frontend';

let frontEndLB = createLoadBalancer(
    COMPONENT_NAME,
    argv.externalIP || '192.168.1.43',
    80,
    80
);
frontEndLB.validate();



let deployment = createDeployment(
    COMPONENT_NAME,
    'vengelmann/cie-frontend',
    [{ name: 'CIE_ENV', value: deployEnv}],
    [{ 'containerPort': 80 }]
);

console.log(YAML.stringify(frontEndLB));
console.log('---');
console.log(YAML.stringify(deployment));