#! /usr/bin/node

const { createLoadBalancer, createDeployment } = require('./util');

const YAML = require('json-to-pretty-yaml');
const argv = require('yargs').argv;
const deployEnv = argv.env;


let frontEndLB = createLoadBalancer(
    'cie-frontend',
    argv.externalIP || '192.168.1.43',
    80,
    80
);
frontEndLB.validate();



let deployment = createDeployment(
    'cie-frontend',
    'vengelmann/cie-frontend',
    [{ name: 'CIE_ENV', value: deployEnv}],
    [{ 'containerPort': 80 }]
);

console.log(YAML.stringify(frontEndLB));
console.log('---');
console.log(YAML.stringify(deployment));