#! /usr/bin/node
const { createService, createDeployment } = require('./util');
const YAML = require('json-to-pretty-yaml');
const argv = require('yargs').argv;


const deployEnv = argv.env;
const COMPONENT_NAME = "cie-api";

let apiSvc = createService(
    COMPONENT_NAME,
    80,
    "http"
);
apiSvc.validate();


let apiDeploy = createDeployment(
    COMPONENT_NAME,
    "vengelmann/cie-api",
    [{ name: "CIE_ENV", value: deployEnv }],
    [{ name: "http", containerPort: 80 }]
);

const svcYml = YAML.stringify(apiSvc);
console.log(svcYml);
console.log("---")
const deployYml = YAML.stringify(apiDeploy);
console.log(deployYml);



