# This is a "duplicate" guacamole instance pointed only at
# the mysql service, for the sole purpose of accessing the
# administrative console. (The instance of guacamole that uses
# OpenID does not have access to the admin console).
apiVersion: v1
kind: Service
metadata:
  name: cie-guac-admin
spec:
  selector:
    app: cie-guac-admin
  ports:
    - name: http
      port: 80
      targetPort: 8080
---
# PV that supports Tomcat server config/libs
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: guac-pv-do
#   labels:
#     type: local
# spec:
#   storageClassName: do-block-storage
#   capacity:
#     storage: 5Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: "/mnt/data"
---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: guac-pvc-do
# spec:
#   storageClassName: do-block-storage
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 5Gi
# ---
kind: ConfigMap
apiVersion: v1
metadata:
  name: guac-settings-config
---
# Guacamole Tomcat server deployment
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cie-guac-admin
  labels:
    app: cie-guac-admin
spec:
  serviceName: cie-guac-admin
  replicas: 1
  selector:
    matchLabels:
      app: cie-guac-admin
  template:
    metadata:
      labels:
        app: cie-guac-admin
    spec:
      containers:
      - image:  guacamole/guacamole
        name: cie-guac-admin
        env:
        - name: GUACD_HOSTNAME
          value: "cie-guacd"
        - name: GUACD_PORT
          value: "4822"
        - name: GUACAMOLE_HOME
          value: "/guac-home"
        - name: MYSQL_HOSTNAME
          value: cie-db
        - name: MYSQL_DATABASE
          value: guacamole_db
        envFrom:
        - secretRef:
            name: cie-db-guac-creds
        ports:
        - containerPort: 8080
          name: cie-guac-admin
        volumeMounts:
        - name: guac-pvc-do #guac-lib-storage
          mountPath: /guac-home/extensions
        - name: guac-settings-storage
          mountPath: /guac-home
      volumes:
      # - name: guac-lib-storage
      #   persistentVolumeClaim:
      #     claimName: guac-pvc-do
      - name: guac-settings-storage
        configMap:
          name: guac-settings-config
      initContainers:
      - name: pgsql-data-permission-fix
        image: busybox
        command: ["/bin/chmod","-R","777", "/data"]
        volumeMounts:
        - name: guac-pvc-do
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: guac-pvc-do
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
      storageClassName: do-block-storage
