import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useEffect } from "react";
import QRious from "qrious";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

function Card({
  onTap,
  selectedTile,
  setSelectedTile,
  tileNumber,
  children,
  backgroundColor,
  textColor,
  selectedTextColor,
}: {
  children: string;
  onTap: (title: string) => void;
  setSelectedTile: (tile: number) => void;
  selectedTile: number;
  tileNumber: number;
  backgroundColor: string;
  textColor: string;
  selectedTextColor: string;
}) {
  useEffect(() => {}, [selectedTile]);
  return (
    <div
      onClick={() => {
        onTap(children);
        setSelectedTile(tileNumber);
      }}
      style={{
        backgroundColor:
          selectedTile === tileNumber ? "black" : backgroundColor,
        color:
          selectedTile === tileNumber
            ? selectedTextColor || "white"
            : textColor,
        flexGrow: 1,
        margin: "20px",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        fontSize: "1.4em",
        borderRadius: "10px",
        fontFamily: "Ariel, sans-serif",
        opacity: "85%",
        transition: "background-color 500ms linear",
      }}
    >
      {children}
    </div>
  );
}

export default function Home() {
  const [contentTitle, setContentTitle] = useState("sdfsdf");
  const [selectedTile, setSelectedTile] = useState(0);
  useEffect(() => {
    var qr = new QRious({
      element: document.getElementById("qr"),
      value: "https://www.codinginenglish.com/?a=dfgdsf",
      size: 200,
    });
  });
  return (
    <>
      <Head>
        <title>cie kiosk</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.vid}>
          <video
            autoPlay
            muted
            loop
            style={{ width: "100vw", height: "100vh", objectFit: "cover" }}
          >
            <source src="/skyscrapers-91744.mp4" type="video/mp4" />
          </video>
        </div>
        <div
          style={{
            display: "flex",
            flexDirection: "column",
            minHeight: "100%",
            minWidth: "30%",
            maxWidth: "30%",
          }}
        >
          <div
            onClick={() => {
              setContentTitle("¿Quiénes somos?");
              setSelectedTile(0);
            }}
            style={{
              margin: "20px",
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              background: "white",
              borderRadius: "10px",
              flexGrow: 1,
            }}
          >
            <div style={{ display: "flex", justifyContent: "center" }}>
              <Image
                style={{ width: "70%", height: "44%" }}
                src="/cie_horizontal_white.jpg"
                alt="me"
                width="1462"
                height="209"
              />
            </div>
          </div>
          <Card
            tileNumber={1}
            selectedTile={selectedTile}
            setSelectedTile={setSelectedTile}
            onTap={setContentTitle}
            backgroundColor="#5C4E4E"
            textColor="white"
          >
            Aprende a programar
          </Card>
          <Card
            tileNumber={2}
            selectedTile={selectedTile}
            setSelectedTile={setSelectedTile}
            onTap={setContentTitle}
            backgroundColor="#FDFAEC"
            textColor="black"
            selectedTextColor="red"
          >
            🗨 Mejora tu inglés
          </Card>
          <Card
            tileNumber={3}
            selectedTile={selectedTile}
            setSelectedTile={setSelectedTile}
            onTap={setContentTitle}
            backgroundColor="#EB7847"
            selectedTextColor="yellow"
            textColor="white"
          >
            $ Consigue Trabajo
          </Card>
          <Card
            tileNumber={4}
            selectedTile={selectedTile}
            setSelectedTile={setSelectedTile}
            onTap={setContentTitle}
            backgroundColor="#005E94"
            textColor="white"
          >
            ¿Para quién es el curso?
          </Card>
        </div>
        <div className={styles.contentbar}>
          <h1 style={{ fontFamily: "Helvetica, sans-serif" }}>
            {contentTitle}
          </h1>
          {getContent(contentTitle)}
          <div
            style={{
              display: "flex",
              alignItems: "center",
              justifyContent: "space-around",
              padding: "20px",
            }}
          >
            <div>
              Inscríbete para más información y actualizaciones sobre el curso,
              clases de muestra, aperturas de matrícula y más.
            </div>
            <div style={{ fontSize: "5em" }}>➔</div>
            <img title={"http://www.codinginenglish.com/?a="} id="qr"></img>
          </div>
        </div>
      </main>
    </>
  );
}
function P({ children }: { children: string }) {
  return (
    <p style={{ fontFamily: "Helvetica, sans-serif", fontSize: "1.15em" }}>
      {children}
    </p>
  );
}
function getContent(title: string) {
  switch (title) {
    case "Aprende a programar":
      return (
        <>
          <P>
            La programación es una de las carreras de crecimiento más alto en el
            mundo. Y hay una escacez de programadores. Por lo tanto, el salario
            de los trabajos de programación suelen ser altos.
          </P>
          <P>
            Nosotros te enseñamos los lenguajes de programaciones de mucho
            utilidad en el mercado de hoy en día -- React y Python (¡el programa
            en que estás leyendo esto está escrito en React!).
          </P>
          <P>
            Pero para poder captar los trabajos que pagan mejor, también es
            necesario tener un buen nivel de inglés.
          </P>
        </>
      );
    case "🗨 Mejora tu inglés":
      return <P>English content</P>;
    case "$ Consigue Trabajo":
      return (
        <>
          <P>
            Nosotros tenemos un enfoque de dos frentes cuando se trata de los
            trabajos para nuestros graduados.
          </P>
          <P>
            Por un lado, te preparamos con una certera de trabajos para poder
            presentar a empleadores potenciales.
          </P>
          <P>
            Por otro lado, nosotros también tenemos una red de empleadores que
            están buscando programadores.
          </P>
        </>
      );
    case "¿Para quién es el curso?":
      return <div>adultos</div>;
    case "¿Quiénes somos?":
      return (
        <>
          <P>
            Coding in English es instituto de programación e inglés. El
            instructor es Vincent Engelmann, que nació aquí en New Jersey y
            enseñó inglés como segundo idioma antes de empezar una carrera en la
            programación.
          </P>
          <P>
            Vincent actualmente es gerente de un equpo de ingenieros de
            software, y también está en contacto constante con una red de
            empleadores de programadores constantemente en busca de nuevos
            talentos.
          </P>
        </>
      );
  }
}
